micronaut:
  application:
    name: appB
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
        cookie:
          enabled: true
eureka:
  client:
    registration:
      enabled: true
    defaultZone: ${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}
