micronaut:
  server:
    port: 9049
    cors:
      enabled: true
  application:
    name: appA
  http:
    services:
      uaa:
  security:
    oauth2:
      clients:
        uaa:
          grant-type: password
          token:
            auth-method: client_secret_basic
            url: /oauth/token
          scopes:
            - openid
          client-id: web_app
          client-secret: changeit
          authorization:
            url: /oauth/authorize
    token:
      jwt:
      propagation:
        enabled: true
        service-id-regex: .*
    intercept-url-map:
      - pattern: /api/*
        access:
          - isAuthenticated()

eureka:
  client:
    registration:
      enabled: true
    defaultZone: http://localhost:8761
    discovery:
      enabled: true
    host: localhost
